### ISSUE TITLE
Create Functional Spec and Project Plan

### ISSUE THREAD

**Issue by mileswatson** [rational-trading/rational-trading#7]
Link: https://docs.google.com/document/d/1YVtzMRgQwNokKf_WSNNOp676QxApx9_KjhSZiaF28jk/edit

The functional specification should include:

 - [x] a general investigation of the problem and its background;
 - [x] the functionality to be provided;
 - [x] the major components of the system;
 - [x] interface specifications for those components;
 - [x] acceptance criteria for the finished product;
 - [x] a management strategy for the group; and
 - [x] technical contributions to be made by each member

The project plan should set out the tasks assigned to each person, taking account of estimated time to complete each task, and dependencies between them. It is important to work to an overall budget of no more than 60 hours per member.

Each member of the group is expected to make a technical contribution, and to gain substantial experience of programming in the course of the project. This might involve test harnesses or scripts, data conversion utilities, a tutorial system, external interfaces, demonstration examples, or other code as appropriate to the project and the individuals in the team.

Your team should draft the functional specification and project plan and send it to your client at least 24 hours before Meeting 2. You should discuss it at the meeting, adapt it as appropriate and send the final version to the client and group project email address within 24hr of the meeting.

**Comment by StefanPitur** [comment]
Updated Project Plan & Functional Specifications after client meeting


[Project Plan.pdf](https://github.com/rational-trading/rational-trading/files/10545902/Project.Plan.pdf)
[Functional Specification.pdf](https://github.com/rational-trading/rational-trading/files/10545901/Functional.Specification.pdf)
